### ISSUE TITLE
Harvesting a PyCSW server running on docker

### ISSUE THREAD

**Issue by x-malet** [ckan/ckanext-harvest#355]
I have a simple PyCSW docker image ([axiom/docker-pycsw](https://hub.docker.com/r/axiom/docker-pycsw)) and it's running perfectly. When I want to harvest this csw server, it raise an error saying: 

[ckanext.harvest.model] Error contacting the CSW server: <urlopen error [Errno 99] Cannot assign requested address>

The CSW server URL is : http://localhost:8000/pycsw/csw.py

Anyone...??

**Comment by metaodi** [comment]
From where do you want to harvest the CSW server? From a local CKAN installation running on localhost? Or from another Docker container running CKAN?

Please provide more detailed information, otherwise it's hard to tell.

It's most likely one of those issues:
1. You want to access the docker container frim another docker container. Assuming you use Docker Compose, you need to use the docker container name instead of localhost:8000 (see https://docs.docker.com/compose/networking/)
2. You try to harvest your local docker container from remote, which does not work as localhost is always local. You need to provide a valid DNS name for this case.

**Comment by x-malet** [comment]
> From where do you want to harvest the CSW server?

From another Docker container running CKAN

> You want to access the docker container frim another docker container. Assuming you use Docker Compose, you need to use the docker container name instead of localhost:8000 (see https://docs.docker.com/compose/networking/)

I tried this but the harverster doesn't recognize the url type.

The Docker-compose file looks like that (:

```
services:
  pycsw:
    container_name: pycsw
    image: axiom/docker-pycsw
    ports:
      - "0.0.0.0:8000:8000"

  ckan:
    container_name: ckan
    image: dcplab/ckan-gin:0.0.5
    links:
      - pycsw
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
  db:
    container_name: db
    image: dcplab/ckan-gin-db:0.0.5
  solr:
    container_name: solr
    build:
      context: ../../
      dockerfile: contrib/docker/solr/Dockerfile
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  ckan_config:
  ckan_home:
  ckan_storage:
  pg_data:
```
